version: '3.8'

services:
  web:
    build: .
    container_name: grupi-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DJANGO_ENV=${DJANGO_ENV:-dev}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS:-https://api-dev.pavops.net:3000,http://localhost:3000}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://api-dev.pavops.net:3000,http://localhost:3000}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-https://api-dev.pavops.net:3000,http://localhost:3000}
      - DATABASE_URL=${DATABASE_URL:-postgres://grupi_user:grupi_password@db:5432/grupi_db}
    volumes:
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
networks:
  default:
    name: grupi-network

