version: '3.8'

services:
  web:
    build: .
    container_name: grupi-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=dev
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=api-dev.grupi.pavops.net,localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://api-dev.pavops.net,http://localhost:3000}
    volumes:
      - ./data:/app/data
      - ./staticfiles:/app/staticfiles
networks:
  default:
    name: grupi-network

