# Generated by Django 5.2.6 on 2025-09-11 03:52
import uuid

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    # Pega o modelo histórico
    User = apps.get_model('core', 'CustomUser')  # (nome_do_app, nome_do_modelo)

    # Define os dados do superusuário
    email = 'admin@email.dev'
    password = 'admin@email.dev'

    if not User.objects.filter(email=email).exists():

        hashed_password = make_password(password)
        user = User(
            id=uuid.uuid4().hex,
            email=email,
            is_staff=True,
            is_superuser=True,
            password=hashed_password
        )
        # Usa set_password para garantir que a senha seja hasheada corretamente
        # Salva o usuário no banco de dados
        user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(create_superuser),
    ]
