# Generated by Django 5.2.6 on 2025-09-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drp',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Regioes'),
        ),
    ]
