# Generated by Django 5.2.6 on 2025-10-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='tried_count',
        ),
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
