# Generated by Django 5.2.6 on 2025-09-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tags',
            field=models.ManyToManyField(related_name='profiles', through='core.UserTags', to='core.tags'),
        ),
    ]
